This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./acronyms.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file acronyms.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file acronyms.acr....done (9 lines written, 0 warnings).
Output written in acronyms.acr.
Transcript written in acronyms.alg.
